"""Training losses: softmax cross-entropy and algebraic power scores.

The power score is the Bregman divergence generated by
phi(t) = (t^a - t) / (a (a - 1)). For a target distribution y and a
prediction p on the simplex it equals, up to a constant in y,

    L_a(p, y) = sum_i p_i^a / a  -  sum_i y_i p_i^(a-1) / (a - 1),

which is strictly proper for every a > 0 and tends to the log score as
a -> 1. With a = 1 - 2^-j (or 1 + 2^-j) all powers are nested square roots.
Predictions come from the radical link p_i = E_n(z_i) / sum_k E_n(z_k), and
p_i^(2^-j) = rho_n(z_i)^(n 2^-j) / S^(2^-j) is evaluated from rho directly so
no probability is ever rounded to zero before it is raised to a power.
"""

from functools import partial

import jax
import jax.numpy as jnp

from algebraic_vision.primitives import _rho_and_slope, _check_order


def smoothed_targets(labels, num_classes, smoothing):
    """One-hot targets mixed with the uniform distribution."""
    onehot = jax.nn.one_hot(labels, num_classes, dtype=jnp.float32)
    return onehot * (1.0 - smoothing) + smoothing / num_classes


def _reduce(values, reduction):
    if reduction == "mean":
        return jnp.mean(values)
    if reduction == "none":
        return values
    raise ValueError(f"unknown reduction {reduction!r}")


def cross_entropy(logits, labels, smoothing=0.0, reduction="mean"):
    """Softmax cross-entropy with label smoothing (the standard loss)."""
    logits = logits.astype(jnp.float32)
    targets = smoothed_targets(labels, logits.shape[-1], smoothing)
    logp = jax.nn.log_softmax(logits, axis=-1)
    return _reduce(-jnp.sum(targets * logp, axis=-1), reduction)


def _nested_sqrt(x, times):
    for _ in range(times):
        x = x * jax.lax.rsqrt(x)
    return x


def _normalize_logits(z, mode, eps):
    if mode == "none":
        return z
    if mode == "center":
        return z - jnp.mean(z, axis=-1, keepdims=True)
    if mode == "rms":
        z = z - jnp.mean(z, axis=-1, keepdims=True)
        return z * jax.lax.rsqrt(jnp.mean(z * z, axis=-1, keepdims=True) + eps)
    raise ValueError(f"unknown logit normalisation {mode!r}")


def _scaled_rho(z, order):
    """rho_n(z) / max rho_n(z) per row, in (0, 1].

    E_i / E_max = (rho_i / rho_max)^n exactly, so working with these ratios
    is the radical counterpart of subtracting the maximum logit before an
    exponential: powers of numbers <= 1 cannot overflow.
    """
    rho, _ = _rho_and_slope(z, order)
    return rho * (1.0 / jnp.max(rho, axis=-1, keepdims=True))


def radical_probabilities(logits, order=8):
    """p_i = E_n(z_i) / sum_k E_n(z_k), the radical counterpart of softmax."""
    _check_order(order)
    e = _scaled_rho(logits.astype(jnp.float32), order)
    for _ in range(order.bit_length() - 1):
        e = e * e
    return e / jnp.sum(e, axis=-1, keepdims=True)


def power_score(logits, labels, alpha_exponent=-3, order=8, smoothing=0.0,
                normalize="none", eps=1.0, reduction="mean"):
    """Power-score loss with the radical link.

    alpha_exponent = -j selects a = 1 - 2^-j (the final model uses j = 6,
    a = 63/64, with order 64); alpha_exponent = +j selects a = 1 + 2^-j.
    Requires order >= 2^j so that E_n^(2^-j) is an integer power of rho.
    """
    _check_order(order)
    j = abs(alpha_exponent)
    if j == 0 or (1 << j) > order:
        raise ValueError("need 1 <= |alpha_exponent| and 2^|alpha_exponent| "
                         "<= order")
    a = 1.0 - 2.0 ** -j if alpha_exponent < 0 else 1.0 + 2.0 ** -j
    z = _normalize_logits(logits.astype(jnp.float32), normalize, eps)
    targets = smoothed_targets(labels, z.shape[-1], smoothing)

    rho = _scaled_rho(z, order)      # ratios to the row maximum, <= 1
    root = rho                       # E_n^(2^-j) = rho^(n 2^-j)
    for _ in range(order.bit_length() - 1 - j):
        root = root * root
    e = root
    for _ in range(j):
        e = e * e                    # E_n = root^(2^j)
    total = jnp.sum(e, axis=-1, keepdims=True)
    q = root / _nested_sqrt(total, j)    # q = p^(2^-j), never underflows
    p = e / total
    if alpha_exponent < 0:
        p_pow = p / q                # p^a      = p^(1 - 2^-j)
        p_pow_m1 = 1.0 / q           # p^(a-1)  = p^(-2^-j)
    else:
        p_pow = p * q
        p_pow_m1 = q
    loss = (jnp.sum(p_pow, axis=-1) / a
            - jnp.sum(targets * p_pow_m1, axis=-1) / (a - 1.0))
    # sum_c y_c^a / (a (a - 1)) makes the loss zero at p = y. It depends only
    # on the smoothing constants, so it is folded into a Python float here
    # and no real-exponent power enters the computation graph.
    k = z.shape[-1]
    hi, lo = 1.0 - smoothing + smoothing / k, smoothing / k
    const = (hi ** a + (k - 1) * lo ** a) / (a * (a - 1.0))
    return _reduce(loss + const, reduction)


# ---------------------------------------------------------------------------
# Fenchel-Young losses: L(z, y) = Omega*(z) + Omega(y) - <z, y>.
#
# For a separable regulariser Omega(p) = sum_i omega(p_i) on the simplex the
# prediction is p_i = phi'(z_i - tau) with phi = omega* and the threshold tau
# chosen so that sum_i p_i = 1; then Omega*(z) = tau + sum_i phi(z_i - tau)
# and grad_z L = p(z) - y, exactly the cross-entropy/softmax gradient form.
# The loss is convex in z, nonnegative, and zero only when p(z) = y.


def _newton_threshold(z, link, link_slope, tail, iters=30):
    """Solve sum_i link(z_i - tau) = 1 for tau.

    f(tau) = sum_i link(z_i - tau) - 1 decreases in tau. At tau = min(z) every
    term is at least link(0) = 1/2, so f >= 0; at tau = max(z) + tail every
    term is at most 1/K by the link's tail bound, so f <= 0. Newton steps
    that leave the current bracket are replaced by bisection.
    """
    lo = jnp.min(z, axis=-1, keepdims=True)
    hi = jnp.max(z, axis=-1, keepdims=True) + tail
    tau = jnp.max(z, axis=-1, keepdims=True)
    for _ in range(iters):
        t = z - tau
        f = jnp.sum(link(t), axis=-1, keepdims=True) - 1.0
        df = -jnp.sum(link_slope(t), axis=-1, keepdims=True)
        lo = jnp.where(f > 0, tau, lo)          # f decreases in tau
        hi = jnp.where(f < 0, tau, hi)
        step = tau - f / jnp.minimum(df, -1e-12)
        bad = (step <= lo) | (step >= hi)
        tau = jnp.where(bad, 0.5 * (lo + hi), step)
    return tau


def _squareplus_link(t):
    """phi'(t) = (1 + t / sqrt(4 + t^2)) / 2, the order-2 radical logistic."""
    return 0.5 * (1.0 + t * jax.lax.rsqrt(4.0 + t * t))


def _squareplus_slope(t):
    r = jax.lax.rsqrt(4.0 + t * t)
    return 2.0 * r * r * r


def _squareplus_parts(z):
    # Tail: link(-d) <= 1/d^2, so d = sqrt(K) + 2 gives sum <= 1.
    tail = float(z.shape[-1]) ** 0.5 + 2.0
    tau = _newton_threshold(z, _squareplus_link, _squareplus_slope, tail)
    t = z - tau
    q = 4.0 + t * t
    root = q * jax.lax.rsqrt(q)
    p = 0.5 * (1.0 + t / root)
    conj = tau[..., 0] + jnp.sum(0.5 * (t + root), axis=-1)  # Omega*(z)
    return p, conj


@jax.custom_vjp
def _fy_squareplus(z, y):
    return _fy_squareplus_fwd(z, y)[0]


def _fy_squareplus_fwd(z, y):
    p, conj = _squareplus_parts(z)
    # Omega(y) = -2 sum_i sqrt(y_i (1 - y_i)) (up to a constant)
    w = y * (1.0 - y)
    omega_y = -2.0 * jnp.sum(w * jax.lax.rsqrt(jnp.maximum(w, 1e-30)), -1)
    loss = conj + omega_y - jnp.sum(z * y, axis=-1)
    return loss, (p, y)


def _fy_squareplus_bwd(res, g):
    p, y = res
    return (g[..., None] * (p - y), None)


_fy_squareplus.defvjp(_fy_squareplus_fwd, _fy_squareplus_bwd)


def _promote(x):
    x = jnp.asarray(x)
    return x.astype(jnp.promote_types(x.dtype, jnp.float32))


def squareplus_fy(logits, labels, smoothing=0.0, reduction="mean"):
    """Fenchel-Young loss of the squareplus potential (all closed form).

    Prediction p_i = (1 + t_i / sqrt(4 + t_i^2)) / 2 with t = z - tau; the
    gradient is p - y. Algebraic: one Newton solve for tau, square roots.
    """
    z = _promote(logits)
    y = smoothed_targets(labels, z.shape[-1], smoothing).astype(z.dtype)
    return _reduce(_fy_squareplus(z, y), reduction)


def squareplus_probabilities(logits):
    return _squareplus_parts(_promote(logits))[0]


def _radical_link(order):
    def link(t):
        return _rs(t, order)

    def slope(t):
        s = _rs(t, order)
        x = t / order
        return s * (1.0 - s) * jax.lax.rsqrt(1.0 + x * x)
    return link, slope


def _rs(t, order):
    rho, _ = _rho_and_slope(-t, order)
    for _ in range(order.bit_length() - 1):
        rho = rho * rho
    return 1.0 / (1.0 + rho)                  # sigma_n(t) = 1/(1 + E_n(-t))


def radical_fy_probabilities(logits, order=8):
    z = _promote(logits)
    link, slope = _radical_link(order)
    # Tail: sigma_n(-d) <= E_n(-d) <= (n / (2d))^n, so
    # d = (n/2) K^(1/n) + 1 gives a sum below one.
    tail = 0.5 * order * float(z.shape[-1]) ** (1.0 / order) + 1.0
    tau = _newton_threshold(z, link, slope, tail)
    return link(z - tau)


def _radical_fy_impl(z, y, order):
    p = radical_fy_probabilities(z, order)
    # Omega*(z) has no closed form for order > 2; the reported value is the
    # Brier score of p (proper, algebraic), the gradient is the exact
    # Fenchel-Young gradient p - y.
    return jnp.sum((p - y) ** 2, axis=-1), p


@partial(jax.custom_vjp, nondiff_argnums=(2,))
def _radical_fy(z, y, order):
    return _radical_fy_impl(z, y, order)[0]


def _radical_fy_fwd(z, y, order):
    value, p = _radical_fy_impl(z, y, order)
    return value, (p, y)


def _radical_fy_bwd(order, res, g):
    p, y = res
    return (g[..., None] * (p - y), None)


_radical_fy.defvjp(_radical_fy_fwd, _radical_fy_bwd)


def radical_fy(logits, labels, order=8, smoothing=0.0, reduction="mean"):
    """Fenchel-Young loss whose link is the radical logistic sigma_n.

    p_i = sigma_n(z_i - tau), sum p = 1, gradient p - y. Close to softmax for
    large n (sigma_n(t) ~ E_n(t) for t << 0).
    """
    _check_order(order)
    z = _promote(logits)
    y = smoothed_targets(labels, z.shape[-1], smoothing).astype(z.dtype)
    return _reduce(_radical_fy(z, y, int(order)), reduction)


def _entmax15_parts(z):
    """1.5-entmax p = [z/2 - tau]_+^2 by the exact sort-based threshold."""
    x = z * 0.5
    xs = -jnp.sort(-x, axis=-1)
    k = jnp.arange(1, x.shape[-1] + 1, dtype=x.dtype)
    s1 = jnp.cumsum(xs, axis=-1)
    s2 = jnp.cumsum(xs * xs, axis=-1)
    mean = s1 / k
    disc = jnp.maximum(mean * mean - (s2 - 1.0) / k, 0.0)
    tau_k = mean - disc * jax.lax.rsqrt(jnp.maximum(disc, 1e-30))
    support = jnp.sum((xs > tau_k).astype(jnp.int32), axis=-1, keepdims=True)
    tau = jnp.take_along_axis(tau_k, support - 1, axis=-1)
    p = jnp.maximum(x - tau, 0.0) ** 2
    return p


@jax.custom_vjp
def _entmax15_fy(z, y):
    return _entmax15_fy_fwd(z, y)[0]


def _entmax15_fy_fwd(z, y):
    p = _entmax15_parts(z)

    def omega(v):
        # Tsallis-1.5 regulariser Omega(p) = (sum p^1.5 - 1) / 0.75.
        return (jnp.sum(v * v * jax.lax.rsqrt(jnp.maximum(v, 1e-30)), -1)
                - 1.0) / 0.75
    loss = jnp.sum(z * p, -1) - omega(p) + omega(y) - jnp.sum(z * y, -1)
    return loss, (p, y)


def _entmax15_fy_bwd(res, g):
    p, y = res
    return (g[..., None] * (p - y), None)


_entmax15_fy.defvjp(_entmax15_fy_fwd, _entmax15_fy_bwd)


def entmax15_fy(logits, labels, smoothing=0.0, reduction="mean"):
    """1.5-entmax Fenchel-Young loss (sparse; sort, cumulative sums, sqrt)."""
    z = _promote(logits)
    y = smoothed_targets(labels, z.shape[-1], smoothing).astype(z.dtype)
    return _reduce(_entmax15_fy(z, y), reduction)


def entmax15_probabilities(logits):
    return _entmax15_parts(_promote(logits))
